// <auto-generated />
namespace RealEstateProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class added_agent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_agent));
        
        string IMigrationMetadata.Id
        {
            get { return "202401292057099_added_agent"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
