// <auto-generated />
namespace RealEstateProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class name_vo_ime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(name_vo_ime));
        
        string IMigrationMetadata.Id
        {
            get { return "202401301359575_name_vo_ime"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
